name: Evaluating 4o-mini chat api with single-line benchmark

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run evaluation
      run: |
        cd scripts
        ./eval.sh ${{ secrets.4o_mini_model_url }} ${{ secrets.4o_mini_api_key }} "chat" "single-line" "gpt-4o-mini-sl.jsonl" "gpt-4o-mini-sl-output.txt"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: eval_results
        path: scripts/gpt-4o-mini*
